#!/bin/bash
#/etc/init.d/netandap
### BEGIN INIT INFO
# Provides: netap
# Required-Start:$remote_fs $syslog
# Required-Stop:$remote_fs $syslog
# Default-Start:2 3 4 5
# Default-Stop:0 1 6
# Short-Description: netap
# Description: This service is used to start my applaction
### END INIT INFO

case "$1" in
        start)
        echo "Connect Internet and Turn on AP."
        nohup /home/pi/whu-wlan.py > /dev/null 2>&1 &
        nohup create_ap wlan0 eth0 SS 844120806 > /dev/null 2>&1 &
        ;;
        stop)
        echo "Stop wifi."
        pkill whu-wlan
        killall create_ap
        killall wifi.sh
        ;;
        *)
        echo "Usage: service netandapt start|stop"
        exit 1
        ;;
esac
exit 0